// Append only to exact c5a3c0ac baseline test source; do not add to current target.
@MainActor
final class Build12FixtureGenerationTests: XCTestCase {
    func testGenerateExactReleasedV10Fixture() async throws {
        let root = URL(fileURLWithPath: "/tmp/pgos-todo-evidence/Build12V10Fixture", isDirectory: true)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        let container = try PersistenceContainerFactory.makeOnDisk(at: root.appendingPathComponent("PersonalGrowthOS.sqlite"))
        let context = container.mainContext
        let date = Date(timeIntervalSince1970: 1_790_000_000)
        let entry = Entry(title: "真实 V10 来源", body: "原文 📌", createdAt: date)
        let renderer = UIGraphicsImageRenderer(size: CGSize(width: 4, height: 4))
        let bytes = try XCTUnwrap(renderer.image { c in UIColor.blue.setFill(); c.fill(CGRect(x: 0, y: 0, width: 4, height: 4)) }.pngData())
        let media = MediaStore(rootURL: root)
        let source = root.appendingPathComponent("fixture.png")
        try bytes.write(to: source)
        let image = try media.storeOriginal(MediaSource(url: source, originalFilename: "fixture.png", contentType: "image/png"))
        entry.images = [ImageMetadata(id: image.id, relativePath: image.relativePath, originalFilename: "fixture.png",
            contentType: "image/png", byteCount: image.byteCount, pixelWidth: image.pixelWidth, pixelHeight: image.pixelHeight,
            checksum: image.checksum, createdAt: date)]
        context.insert(entry)
        context.insert(EntryPin(entryID: entry.id, pinnedAt: date))
        context.insert(EntryFollowUp(entryID: entry.id, body: "后续补充", createdAt: date))
        context.insert(try EntryExternalSource(entryID: entry.id, source: CaptureSource(url: "https://example.com/v10", title: "原始分享", capturedAt: date, captureMode: .selectedContent)))
        context.insert(CaptureImportReceipt(id: UUID(), importedAt: date))
        let habit = Habit(name: "保持习惯", normalizedName: "保持习惯", createdAt: date)
        context.insert(habit)
        let log = HabitLog(habitID: habit.id, occurredAt: date, isCompleted: true, quantity: 3, unit: "次", linkedEntryID: entry.id, createdAt: date)
        context.insert(log)
        context.insert(HabitLogDayMetadata(habitLogID: log.id, localDayIdentifier: "2026-09-22", localTimeZoneIdentifier: "Asia/Shanghai", provenance: .capturedAtWrite))
        let goal = Goal(kind: .flag, title: "旧目标", normalizedTitle: "旧目标", createdAt: date)
        context.insert(goal)
        context.insert(GoalLifecycleEvent(goalID: goal.id, kind: .created, occurredAt: date, createdAt: date))
        let tag = Tag(displayName: "旧标签", normalizedName: "旧标签", createdAt: date)
        context.insert(tag)
        context.insert(ObjectLink(sourceType: .entry, sourceID: entry.id, targetType: .tag, targetID: tag.id, kind: .entryUsesTag, createdAt: date))
        context.insert(WeightRecord(weightKilograms: 65.5, recordedAt: date, createdAt: date))
        let week = try WeeklyReviewPeriod(containing: date)
        context.insert(WeeklyReview(weekIdentifier: week.identifier, periodStart: week.start, periodEnd: week.end, rememberedText: "保留回顾", focusText: "保留重点", createdAt: date))
        try context.save()
        _ = try HabitAnalyticsMigrationBootstrap.apply(context: context, now: date)
        let lease = try await ImportExportService(context: context, mediaStore: media).exportPackage()
        try FileManager.default.copyItem(at: lease.url, to: root.appendingPathComponent("expected-v6.zip"))
        lease.cleanup()
        try Data("c5a3c0ac859efc3ffa4e5d9f77909ec43565c871\nSchema V10, generated by exact archived baseline source\n".utf8).write(to: root.appendingPathComponent("SOURCE.txt"))
        XCTAssertEqual(try context.fetchCount(FetchDescriptor<Entry>()), 1)
    }
}
